### ISSUE TITLE
Grouping (video cards)

### ISSUE THREAD

**Issue by luxzg** [jdegene/steamHWsurvey#1]
Thanks for this data treasure!

I did notice one thing, though I've only looked at 2020-2022 data.

Some video card names have stuff like "(R)" or "Series" added to the names, and thus we get duplicates, eg:

- AMD Radeon RX 590
- Intel Iris Plus Graphics
- Intel UHD Graphics
- Intel UHD Graphics 630

Probably not all that important, but if you care you can look into grouping them automatically, and removing these (R) and Series from the names. But you may also just close this issue ;D

Thanks for the data!

**Comment by jdegene** [comment]
Thanks for the heads up, I hadn't noticed yet. I think I will still leave the data as raw as I got it, but added a note to the readme so others will be aware!

Cheers!
