### ISSUE TITLE
Missing 'Steam users with VR Headsets' stat

### ISSUE THREAD

**Issue by mrxz** [jdegene/steamHWsurvey#5]
In contrast to the other stats, the VR headset percentages aren't expressed as percentages of the Steam user base, but instead of the Steam users _with a VR headset_. For that reason Steam includes an additional stat at the bottom for the percentage of users with a VR headset:
![image](https://github.com/user-attachments/assets/05005b88-d34b-4323-9169-1b8426c42b23)

It seems that this is missing from the scraped data. A quick look at the source reveals that this particular row is missed since it has an additional `total_row` class, which the current script doesn't match against. Simply including this row in the current setup would place it under the category 'VR Headsets' which would be confusing.

Not sure what the best way to include the stat would be, if at all. But it's probably worth including or otherwise documenting its omission.

**Comment by jdegene** [comment]
Oh, you are right, good catch. I extended the script (https://github.com/jdegene/steamHWsurvey/commit/67e8bda3e63776dbae6dc7553023dfc3797602ae) to fetch these "totals" rows as well... the downside is that they are now treated as normal data... so people must be a bit cautious when using these numbers. I've added an info/warning about this in the readme... thx :)
